/*
This file is automaticly generated by rbc.py script. Please do 
not modify it until you know what you're doing.
*/

#ifndef _TEST0_H_
#define _TEST0_H_

#define CTRL_REG 0
#define CTRL_REG_A_OFFSET 6
#define CTRL_REG_B_OFFSET 0
#define CTRL_REG_B 1
#define CTRL_REG_B_CX_OFFSET 5
#define CTRL_REG_B_DX_OFFSET 0
#define TEST_REG0 2
#define TEST_REG0_TB_OFFSET 0
#define TEST_REG0_BX_OFFSET 3

#endif /* _TEST0_H_ */