/*
This file is automaticly generated by rbc.py script. Please do 
not modify it until you know what you're doing.
*/

#ifndef _// {name}_H_
#define _// {name}_H_

// {definitions}

#endif /* _// {name}_H_ */